title: My favorite Codes
theme: jekyll-theme-leap-day
locale: en_US
description: Place where I post my codes
search: true
url: https://codinglegend121.github.io/Main-Repo/


owner:
  name: Charan Adhish Vengatesh
  email: charan.adhish@gmail.com
  github: CodingLegend121
